Variables:

  jira-connector:
  
    # Url to jira server
    Url: ""

    # Url to jira server v3
    Urlv3: ""

    # Username to connect to the Jira server
    Username: ""

    # Password to connect to the Jira server
    # [password]
    Password: ""
